name: "format code"

# run on pull requests to develop
on:
  pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # fetch everything to be able to compare with any ref
          fetch-depth: 0

      - name: check
        run: |
          
          sudo apt install  -y clang-format clang-tools python3 git
          git --no-pager diff --name-only --diff-filter=ACMRT ${{github.event.pull_request.base.sha}} ${{ github.event.pull_request.head.sha }}
          echo ${{ github.head_ref }} 
          git checkout ${{github.event.pull_request.base.sha}}
          git --no-pager diff --diff-filter=ACMRT ${{github.event.pull_request.base.sha}}  ${{ github.event.pull_request.head.sha }}| clang-format-diff -p1 -i
          modified_files=$(git status | grep "modified:" | awk '{print $2}')
          if [ ${#modified_files[@]} -gt 0 ];
          then
              for file in $modified_files
              do

                echo "git diff $file"
                git diff $file

              done
              exit 1
         fi 
      
